production:
 sessions:
   default:
     uri: ENV['MONGOLAB_URI']
     options:
       consistency: :strong
       max_retries: 30
       retry_interval: 1
       timeout: 15
       safe: true
       refresh_interval: 10

development:
  clients:
    default:
      database: roadtable_api_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: roadtable_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
